# Generated by Django 3.2.6 on 2021-10-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikelnr', models.IntegerField()),
                ('titel', models.CharField(max_length=100)),
                ('winzer', models.CharField(choices=[('ASC', 'Arndt Schnabel'), ('ASE', 'Andreas Schnabel'), ('GRO', 'Eckehart Groehl'), ('KRO', 'Markus Krollmann'), ('PSC', 'Philip Schnabel St. Martinshof'), ('SEY', 'Seyberth'), ('WHS', 'Winzer Hof Schnabel')], max_length=3)),
                ('weinart', models.CharField(choices=[('rot', 'rot'), ('rose', 'rose'), ('weiss', 'weiss'), ('schaumwein-rot', 'schaumwein-rot'), ('schaumwein-rose', 'schaumwein-rose'), ('schaumwein-weiss', 'schaumwein-weiss')], max_length=20)),
                ('rebsorte', models.CharField(choices=[('Riesling', 'Riesling'), ('Mueller-Thurgau', 'Mueller-Thurgau'), ('Silvaner', 'Silvaner'), ('Kerner', 'Kerner'), ('Weissburgunder', 'Weissburgunder'), ('Grauburgunder', 'Grauburgunder'), ('Bacchus', 'Bacchus'), ('Scheurebe', 'Scheurebe'), ('Huxelrebe', 'Huxelrebe'), ('Gewuerztraminer', 'Gewuerztraminer'), ('Chardonnay', 'Chardonnay'), ('Sauvignon Blanc', 'Sauvignon Blanc'), ('Spaetburgunder', 'Spaetburgunder'), ('Dornfelder', 'Dornfelder'), ('Portugieser', 'Portugieser'), ('Schwarzriesling', 'Schwarzriesling'), ('Regent', 'Regent'), ('Saint Laurent', 'Saint Laurent'), ('Cabernet Sauvignon', 'Cabernet Sauvignon'), ('Merlot', 'Merlot')], max_length=30)),
                ('ausbau', models.CharField(choices=[('TR', 'trocken/herb'), ('HTR', 'halbtrocken/feinherb'), ('M', 'mild/suess')], max_length=20)),
                ('land', models.CharField(choices=[('DE', 'Deutschland'), ('AT', 'Oesterreich')], max_length=20)),
                ('region', models.CharField(choices=[('Rheinhessen', 'Rheinhessen'), ('Rheingau', 'Rheingau'), ('Mittelrhein', 'Mittelrhein'), ('Mosel', 'Mosel'), ('Nahe', 'Nahe'), ('Pfalz', 'Pfalz'), ('Weinfranken', 'Weinfranken'), ('Baden', 'Baden')], max_length=30)),
                ('jahrgang', models.IntegerField()),
                ('inhalt', models.DecimalField(decimal_places=2, max_digits=3)),
                ('alk', models.DecimalField(decimal_places=2, max_digits=3)),
                ('saeure', models.DecimalField(decimal_places=1, max_digits=2)),
                ('restzucker', models.DecimalField(decimal_places=1, max_digits=2)),
                ('sulfite', models.BooleanField()),
                ('added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
