# Generated by Django 3.2.6 on 2021-10-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wein',
            name='alk',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
